spring:
  application:
    name: website
  datasource:
    url: jdbc:postgresql://localhost:5432/practice_db
    username: postgres
    password: SpainPrince21
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    async:
      request-timeout: 3600000
server:
  port: 8080